language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: NWyA7p/IamkQTHaa/pTC1AZquNeY5n6b6ceyG8yenw+pVXw3fEba1JsCg7E1kF+fqf0jn+NIpA0CMoGTz9hw9WVy4j9mV6hcult+06gCEJX/xlSYW710qwceoN0QbJsvSbBG0N5iIUxPwgh/DkRy/8yL/NTbBlAoRBFxo9obalAbAmFnoZk4oYx77FWdsYMa/eAta+a4uM4RkdbO1KVY9nKpRB0OcEfV1nkIFUAvnhXPDEhwDENVVgJiCRYu1o/kg4EaUEPQpiZJQVCdA7/fC0IlDwK5eQfibvgGLpYEu4GDWnVecZyHOjPXcvBplrH3lsUSd/OJPhmnP7IjiWp3LjpYuHUdg7NuIPxVa7FeH+NimDFsHJSs9PpGCov1HhQ0RKsDqtalPcoUjBacj0SG8yu2kWSeNVV9lnji7Atk1jtutxpRF9Byb/M9HhePE0CnjG9IFm83VRRe6YERTDjznYjRV2inzmEbOnrHnSYtBTIaHr8oWHOKdwjpp1vY+o6doTkslmzYYec90WhzYHc3IAZyA9VQBNxDfcHkH/2NuL7H+cHHXpizVz00hVFhex4UHXzo4/zyj4MooqS4xSvgCTkXGXoXNOmc+1OFhPQpY1DIuo+/JsXn+mmW2YHzEox1TRu1zgcPLJDc+WLDQQgExnQn5DImts+wDci+xhpEUGY=
  app: factorio-state-machine
  on:
    repo: acbabis/factorio-state-machine
